### ISSUE TITLE
Simplifying the creation of Exceptions

### ISSUE THREAD

**Issue by Asha20** [rxing-core/rxing#10]
Currently, exceptions are being created like this:

```rust
Exceptions::IllegalArgumentException(Some(
  "file does not exist".to_owned(),
))

Exceptions::FormatException(Some("could not create image buffer".to_owned()))

Exceptions::IllegalArgumentException(None)
```

I'm thinking we could simplify the code by introducing helper functions to construct them, so we end up with this:

```rust
Exceptions::illegalArgument("file does not exist")

Exceptions::format("could not create image buffer")

Exceptions::illegalArgumentEmpty() // better function name TBD
```

What do you think? I can open a PR if it looks like a good idea to you.

**Comment by hschimke** [comment]
Are you thinking the format function would take a String and the other an &str?

**Comment by Asha20** [comment]
I meant it like this:

```rust
impl Exceptions {
  pub fn illegalArgument<I: Into<String>>(x: I) -> Self {
      Self::IllegalArgumentException(Some(x.into()))
  }

  pub fn illegalArgumentEmpty() -> Self {
      Self::IllegalArgumentException(None)
  }

  pub fn format<I: Into<String>>(x: I) -> Self {
      Self::FormatException(Some(x.into()))
  }

  pub fn formatEmpty() -> Self {
      Self::FormatException(None)
  }

  // Plus more helpers for each kind of exception...
}

This way, the caller can pass both `&str` and `String` effortlessly.

**Comment by hschimke** [comment]
Sometimes I forget neat rust stuff like that! It never occurred that you could generic with `Into<String>` even though i used it for `Into<f64>` in several places.

I like this idea. I had been wanting a cleaner way to handle this since I abandoned my original way of doing it that didn't use the Option<String> and had a mess of `IllegalArgumentException(String::default()` sprinkled all over.

**Comment by hschimke** [comment]
I'm torn on naming here. I think the most common case is an empty message. That makes me wonder if we should make the default function generate the empty message and have the version with the message include a "detailed" suffix, or something similar. I don't have a strong preference either way, thoughts?

**Comment by Asha20** [comment]
Yep, you're right, empty messages are more common. How about this, then?

```rust
pub const illegalArgument: Self = Self::IllegalArgumentException(None);

pub fn illegalArgumentWith<I: Into<String>>(x: I) -> Self {
    Self::IllegalArgumentException(Some(x.into()))
}
```

And on the caller side:

```rust
return Err(Exceptions::illegalArgument);
return Err(Exceptions::illegalArgumentWith("foo"));
```

We can make the `None` case `const`, so that you don't need to put the parentheses for the function call each time. Also maybe use the `with` suffix for the `Some` case?

**Comment by hschimke** [comment]
This looks good to me.

**Comment by SteveCookTU** [comment]
Just wanted to put in my two cents, I think if anything `Exceptions` could be redesigned to be more Rustic. 

For example with the `thiserror` crate:

```
use thiserror::Error;

#[derive(Error, Debug, PartialEq, Eq)]
pub enum Exceptions {
    #[error("Failed to parse generation{}", if .0.is_empty() { String::new() } else { format!(" - {}", .0) })]
    IllegalArgumentException(&'static str),
    ...
}
```

This removes a lot of the boilerplate and is somewhat more readable. I haven't gone through enough of the source to see if non static string slices would need to be passed but if so then it's as simple as changing the `&'static str` to `String` and replace `String::new()` with `.0`.

For when a string is not needed, `String::new()` is a `const fn` which can be used to declare a global empty type if necessary.

That formatting in the macro is a rough idea but it accepts the same formatting of `std` macros such as `println!`

**Comment by hschimke** [comment]
Interesting, I hadn’t looked too hard into any of the error handling crates. The library has a pretty wide mix of static strings and formatted Strings that are used for errors. If I had to guess I’d say it’s 60-70 no-text, with the remainder split 2/3 static strings.

**Comment by hschimke** [comment]
I like that we can basically take what @Asha20 has done and include thiserror. I’ve never used it before, so I’d like to poke at that crate a little bit, but otherwise it seems more robust than what I’ve done with enum impl blocks and match statements.
