### ISSUE TITLE
Possible Use for Generics

### ISSUE THREAD

**Issue by SteveCookTU** [rxing-core/rxing#14]
I was playing around from "building from scratch" by deleting files and rewriting with generics in mind and it seems to start off well.

I'm curious if binary size or performance are preferred in the context of the library because with generics there should be an increase in performance instead of accessing vtables through dynamic dispatch but binary size will increase.

Wanted to open this issue to bring up the discussion of the possibility and implementation.

**Comment by hschimke** [comment]
Which parts were you looking at doing this for? The first to come to mind for me was: Binarizer / Luminance Source / Reader. That chain, which is basically how you setup an entire reader, is probably ripe for switching to generics. I built one out that did it, but I wasn’t 100% comfortable with PhantomData, which I thought it might need, so I didn’t complete that task.

To answer the question: When writing it I put my priorities in this order.
1. Correctness
2. Readability
3. Speed and Performance
4. Memory performance
5. Binary size

There is probably something to be said for keeping the binary size small, but I didn’t put it high on my list of worries while doing the port.

**Comment by SteveCookTU** [comment]
> Which parts were you looking at doing this for? The first to come to mind for me was: Binarizer / Luminance Source / Reader. 

These elements are exactly what I was playing with in my fork.

> I built one out that did it, but I wasn’t 100% comfortable with PhantomData, which I thought it might need, so I didn’t complete that task.

I was able to avoid this with the use of GATs. The Binarizer would contain a type definition that requires a struct with LimunanceSource implemented. I'll see if I can recreate it in a draft PR so demonstrate. I think to do so the first requirement would be to have the macro in this repo as well so the changes could be reflected.

With a draft in mind, performance and binary size could be compared after. Also since dynamic dispatch would be introduced, memory performance make see a slight boost (less boxing/allocations).

**Comment by hschimke** [comment]
Im super interesting see how you did this! It's been on my todo list since the third week of the project. 

Im going to try to merge the two repos later this week, if I have enough downtime.

**Comment by SteveCookTU** [comment]
I would attempt a PR for just converting to workspace myself but I have no clue how this affects publishing on cargo and possibly other things

**Comment by hschimke** [comment]
Yeah, me either. I'm going to have to do some reading and figure it out. I would also like to try to bring in some of the commit history from the other repo so I am going to try to learn if that's even possible. I'm also remote all this week and part of next so I'm a little slow.

**Comment by SteveCookTU** [comment]
Everything seems to be going smoothly up until the multi format readers which utilize dynamic dispatch for reading. Going to play around with it and see if I can come up with a way where the readers don't need to be stored in memory

**Comment by hschimke** [comment]
Closed with the merge of #20
