### ISSUE TITLE
get in BitMatrix goes out of bounds for Maxicode in certain image.

### ISSUE THREAD

**Issue by Olssdani** [rxing-core/rxing#28]
The image below makes the library crash because the algorithm gives a point outside of the image. I have already made a fix, and the PR is on its way.

![test](https://user-images.githubusercontent.com/16461943/226611447-be6041dc-5b21-42fe-827b-068ccc59082c.png)

**Comment by hschimke** [comment]
Thanks for the PR, I'm reviewing it now.

**Comment by hschimke** [comment]
I am going to merge #29, and adjust the internal working of the `BitMatrix` struct to return `false` if a requested point is out of bounds. I will document in the comments. I don't know if I think it's exactly the correct way to handle things, but the idea of having the entire library have to handle an Option or Result for every `get` or `get_point` seems sorta bad.

In the original java they just let the `ArrayOutOfBoundException` fly and caught it as part of their regular error handling, sometimes using it to detect if a transform had resulted in an impossible final set of points.

I'm open to revisiting this if it is the wrong choice.

**Comment by hschimke** [comment]
I also added this image as test case `github_issues::issue_28`
