### ISSUE TITLE
Pure ITF barcode not being decoded

### ISSUE THREAD

**Issue by filipesilva-l** [rxing-core/rxing#50]
Hi, I was trying to decode an image that is purely a barcode but, even with the --pure-barcode true flag, the library is not being able to decode the image.

Here is an example:
![134](https://github.com/rxing-core/rxing/assets/30537113/16acfb7a-4a41-4b15-af78-7ccf061e72bd)

Thanks!

**Comment by hschimke** [comment]
This is a needed enhancement to the library. I am actively investigating its addition.

**Comment by hschimke** [comment]
This release has been published to crates.io and to rxing-wasm v0.2.9

**Comment by filipesilva-l** [comment]
Thanks a lot!
