### ISSUE TITLE
encode code_128 not work

### ISSUE THREAD

**Issue by ti-integra** [rxing-core/rxing#56]
I have try use encode with code_128 e show this mensage

```Couldn't encode: IllegalArgumentException - No encoder available for format UNSUPORTED_FORMAT```

the error is in [this line](https://github.com/rxing-core/rxing/blob/b1753134e5eb1db02c3e24765821db16cba3a892/src/barcode_format.rs#L144)

is write code_129 and not code_128

**Comment by hschimke** [comment]
Good find, thank you. I will get this patched in the next release. For now please use one of the other string constants such as "code128" to access this encoder.
