### ISSUE TITLE
Cannot encode DataMatrix bigger than 48x48

### ISSUE THREAD

**Issue by snail-with-tea** [rxing-core/rxing#59]
When encoding datamatrix without hints with input long enough for output to be bigger than 44x44 IndexOutOfBoundsException is thrown.
Expected behavior: writer generates datamatrix bigger, then 48x48.

Setting MinSize to something bigger than 48x48 also produces this error.

**Comment by hschimke** [comment]
I think I have found the issue. I'm working on a fix.

**Comment by hschimke** [comment]
Looks like a problem with the ECC code for larger symbols. Works correctly for smaller symbols because there is only one ecc block

**Comment by hschimke** [comment]
Looks like I have a fix. I'll run a few more tests and try to have it out this evening or tomorrow.

**Comment by hschimke** [comment]
this fix is available in v0.6.4 on crates.io. please re-open if the issue is not fixed.
